version: '3.8'
 
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 3Bird-GuardianRSS_app
    ports:
      - "9001:9000"
    volumes:
      - .:/var/www/html
    networks:
      - laravel_network
    restart: unless-stopped
    depends_on:
      - db
 
  nginx:
    image: nginx:alpine
    container_name: 3Bird-GuardianRSS_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_network
    depends_on:
      - app
 
  db:
    image: postgres:15
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_DB: 3Bird-GuardianRSS_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    networks:
      - laravel_network
 
volumes:
  db_data:
 
networks:
  laravel_network:
    driver: bridge